apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: mychart
type: application
version: 0.1.0
dependencies:
  - name mychart
    version: 0.1.0
    repository: oci://harbor.test.myfaccloud-301.com/demogitops